# Generated by Django 2.0 on 2017-12-07 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('multi', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='pos',
        ),
        migrations.AddField(
            model_name='biz',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
