# Generated by Django 2.0 on 2017-12-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171207_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pos',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
