# Generated by Django 2.0 on 2017-12-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171207_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
