# Generated by Django 2.0 on 2017-12-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_biz_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biz',
            name='multi',
        ),
    ]
