# Generated by Django 2.0 on 2017-12-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp',
            new_name='user',
        ),
    ]
