# Generated by Django 2.0 on 2017-12-07 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_biz_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sunday_start', models.TimeField()),
                ('sunday_end', models.TimeField()),
                ('monday_start', models.TimeField()),
                ('monday_end', models.TimeField()),
                ('tuesday_start', models.TimeField()),
                ('tuesday_end', models.TimeField()),
                ('wednesday_start', models.TimeField()),
                ('wednesday_end', models.TimeField()),
                ('thursday_start', models.TimeField()),
                ('thursday_end', models.TimeField()),
                ('friday_start', models.TimeField()),
                ('friday_end', models.TimeField()),
                ('saturday_start', models.TimeField()),
                ('saturday_end', models.TimeField()),
                ('biz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Biz')),
            ],
        ),
    ]
