# Generated by Django 2.0 on 2017-12-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171208_0422'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='emp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Emp'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
